"""
GPIO Pin-Konfiguration für Unkraut-2025
"""

# Motor Pins
MOTOR_LEFT_FORWARD = 18
MOTOR_LEFT_BACKWARD = 19  
MOTOR_RIGHT_FORWARD = 20
MOTOR_RIGHT_BACKWARD = 21
MOTOR_ENABLE_LEFT = 12
MOTOR_ENABLE_RIGHT = 13

# Sensor Pins
ULTRASONIC_TRIGGER = 23
ULTRASONIC_ECHO = 24
SOIL_MOISTURE_PIN = 25
TEMPERATURE_PIN = 4

# LED/Status Pins
STATUS_LED_GREEN = 16
STATUS_LED_RED = 17
STATUS_LED_BLUE = 27

# Camera
CAMERA_DEVICE = 0  # /dev/video0
